experiment:
  name: "stitch_cube_map_small"
  seed: 1

data:
  train_dataset: "/home/mg515/ragi/360SP-data/panoramas"
  fov: 180
  canvas_size: [1792, 896]
  overlap: 0.5
  jitter:
    random_seed: 1
    roll: 1.0
    pitch: 1.0
    yaw: 1.0
    translate: 0.5
    brightness: 1e-1
    contrast: 1e-2
    color_jitter: 1e-2

train:
  epochs: 50
  optimizer: "adam"
  batch_size: 1
  lr: 1e-4
  num_workers: 4
  grad_clip: 3
  weight_decay: 1e-4

log:
  save_interval: 1
  log_interval: 100

model:
  homography: 1
  mean: 0.5, 0.5, 0.5
  std: 0.5, 0.5, 0.5
  local_adj_limit: 0.1