experiment:
  name: "stitch_ssim_kl_l2_affine"
  seed: 1

data:
  train_dataset: "/home/mg515/ragi/360SP-data/panoramas"
  fov: 180
  canvas_size: [1024, 512]
  overlap: 0.5
  jitter:
    random_seed: 1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    translate: 0.0
    brightness: 0
    contrast: 0
    color_jitter: 0

train:
  epochs: 50
  optimizer: "adam"
  batch_size: 2
  lr: 1e-4
  num_workers: 10
  grad_clip: 3
  weight_decay: 1e-4
  lambda1: 0.2
  lambda2: 0.1
  l_num: 2
  beta: 1e-3 # KL loss weight
log:
  save_interval: 3000
  log_interval: 10

model:
  homography: 1
  mean: 0.5, 0.5, 0.5
  std: 0.5, 0.5, 0.5
  local_adj_limit: 0.1
  record_weights: true
  record_warped: true
  kl: true